gnosis/pm-trading-ui

.babelrc, webpack.dev.config.js, webpack.prod.config.js
DESCRIPTION
This PRs introduces source-maps for being used with Chrome DevTools only when developing.
TESTS DONE
I have tested the app running in bash
```
NODE_ENV=development npm start
NODE_ENV=production npm start
```
Checked both versions run the correct scripts and loaded the app.
=> Add source maps in webpack configuration

src/actions/market.js, src/components/OutcomePriceChanged/index.js, src/config.json, src/containers/ModalOutcomePriceChanged/index.js, src/containers/modals.js, src/utils/marginPrice.js, src/utils/marginPrice.spec.js
**Due Diligence**
**Description**
This PR reject transactions when buying tokens if the difference is higher than the 5%. Please double check the ```allowedRangePrice``` function and tests.
=> PM-154 Reject transactions with more 5% diff in prices

src/components/MarketBuySharesForm/index.js
**Before:** 
`You're trying to invest more OLY tokens than you have.`
**After:**
`You're trying to invest more ETH tokens than you have.`
=> Feature PM-202 Change OLY to ETH

src/components/MarketBuySharesForm/index.js, src/components/MarketShortSellForm/index.js, src/components/ScalarSlider/index.js
Word "bet" is replaced with "trade" everywhere + some indent/lint fixes.
Actual changes are:
- Line 145, 237 in `src/components/MarketBuySharesForm/index.js`
- Line 157 in `src/components/MarketShortSellForm/index.js` (I'm not sure If we need this component)
- Line 42, 54 in `src/components/ScalarSlider/index.js`
=> Feature PM-212 Replace 'bet' with 'trade'

src/components/MarketList/marketList.less
In this PR I have increased the margin of the first block (where we show the Create Market) button, making it more consistent. 
**BEFORE:** 
**AFTER:**
=> Feature PM-19 show markets up

src/components/Dashboard/dashboard.less, src/components/Dashboard/index.js, src/components/MarketList/marketList.less
- Fix css for market list controls in case user is not an admin
**BEFORE:**
**AFTER:**
- Fix widget headings:
`New markets` > `Latest markets`
`Soon-Closing markets` > `Next markets`
- Change margin for dashboard buttom from 50 to 42 so its the same as in MarketList, also added bottom margin for stats so if the button is not shown it wont be as before pic for MarketList
=> Feature PM-217 Changed widget headings, Fix CSS for market list controls/dashboard

src/components/Dashboard/index.js
Increase space for columns in dashboard market list items, add a space before currency name.
**BEFORE:**
**AFTER:**
=> BUG PM-238 Align the words

src/components/FormInput/formInput.less, src/components/FormInput/index.js
Make error span absolutely positioned to prevent spacing change
**Originally:**
**Before:**
**After:**
=> PM-223 Make error span absolutely positioned to prevent spacing change

src/api/gnosis.js
If the contract exists, will exit the function as intended. Will also ensure WinningsRedemption event is fired.
=> Fix redeemWinnings flow

src/api/gnosis.js
This also fixes the `postMessage` issue: browser plugins like MetaMask use `postMessage` to communicate with injected scripts. `postMessage` requires that the message can be serialized completely (i.e. is something akin to plain old data/JSON).
I dunno why `marketFactory` was specified, but the `event.redeemWinnings.estimateGas` call is actually a call to the [Ethereum JS API](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethestimategas) and not routed through GnosisJS code (so it tries to communicate with MetaMask by default), and specifying `marketFactory` to be the `StandardMarketFactory` Truffle abstraction causes `postMessage` to choke while trying to serialize `StandardMarketFactory` for MetaMask. The Ethereum JS `estimateGas` contract calls takes the same arguments as …
=> Remove unused parameters to estimateGas calls

package.json, webpack.prod.config.js
This PR enables parallelisation and removes compression on files when running the UglifyPlugin in the prod webpack file.
Had to do this because compilation was stuck compiling assets.
=> Adding compress and parallel options to Uglify Plugin

src/components/MarketList/marketList.less
This is so clicks on market list items are not blocked on narrow width displays
Just thought I would start up the [Cipher support](https://www.cipherbrowser.com/)
=> Make reflowable column inline-block to shrinkwrap

package.json, src/components/MarketWithdrawFeesForm/index.js
**BEFORE**:
After pressing `Withdraw fees` transaction is not triggered.
**AFTER**:
After pressing `Withdraw fees` transaction is triggered.
=> PM-229: Fix "Withdraw fees" button not triggering the transaction

src/components/MarketDetail/index.js, src/containers/MarketDetailPage/index.js
**BEFORE**:
Everyone can see market creator's name/address from whitelist.
**AFTER**:
Only whitelisted accounts can see market creator's name/address.
=> PM-220: Show market creator only to whitelisted accounts

.babelrc, package.json, src/api/rest.js, src/api/utils/fetch.js, src/routes/marketlist/store/actions/addMarkets.js, src/routes/marketlist/store/actions/fetchMarkets.js, src/routes/marketlist/store/actions/index.js, src/routes/marketlist/store/models/bound.js, src/routes/marketlist/store/models/bounds.js, src/routes/marketlist/store/models/index.js, src/routes/marketlist/store/models/market.js, src/routes/marketlist/store/models/outcome.js, src/routes/marketlist/store/reducers/market.builder.js, src/routes/marketlist/store/reducers/market.js, src/routes/marketlist/store/reducers/market.spec.js
**Due Diligence**
**Description**
This PR creates the market list route (folders). Also, it includes the reducer and necessary actions for fetching, manipulate and store data (simplified) in the store. 
It includes tests based on features, using the "Builder" pattern. Those tests simulate a "real" redux store.
**DevNotes**
Additionally, it includes an update to Babel 7 and a simplified configuration for running tests on Travis.
The Builder pattern allows us to create markets in this way:
```
cons aEthereumMarket = aMarket()
.withTitle('What will the number of Ethereum transactions be on January 3rd, 2018?')
.withDate('2018-01-03T12:00:00')
.withVolume('857142857142872776')
.withType(MARKET_SCALAR)
.withOutcomes()
.withBounds('500000', '1250000', 'Txs')
.get()
```
Which simplifies …
=> Feature PM-411 creation action reducers market list route

src/components/Header/index.js, src/routes/index.js
This PR fixes:
- Not redirecting from `markets/*invalid id*` paths
- App crash if redirecting multiple times to `/` and then to `markets/list`
=> BUG PM-442: Fix redirection problems

src/components/MarketDetail/index.js
We are calculating gas cost every time on market detail page, regardless of whether the market is resolved or not. When the market is not resolved, it would raise this error: 
```
Error: gas required exceeds allowance or always failing transaction
```
The reason for this is in smart contract function redeemWinnigs:
```
function redeemWinnings()
public
returns (uint winnings)
{
// Winning outcome has to be set
➡️require(isOutcomeSet);
// Calculate winnings
winnings = outcomeTokens[uint(outcome)].balanceOf(msg.sender);
// Revoke tokens from winning outcome
outcomeTokens[uint(outcome)].revoke(msg.sender, winnings);
// Payout winnings
require(collateralToken.transfer(msg.sender, winnings));
WinningsRedemption(msg.sender, winnings);
}
```
Since outcome was not set, the simulated transaction …
=> BUG: Fix failing estimateGas call

src/integrations/metamask/index.js
Previously we used to check `window.web3.currentProvider.constructor.name === 'MetamaskInpageProvider'`
With metamask v4, constructor got minified and now the name is `f`, don't know is the change was planned but I think relying on a bool variable inside the provider is better than on a constructor's name.
https://github.com/MetaMask/metamask-extension/issues/3372
**QUESTION**:
Should we use both ways? 
```
(window.web3.currentProvider.constructor.name === 'MetamaskInpageProvider' || window.web3.currentProvider.isMetaMask)
```
=> Change the way to identify metamask

.babelrc, config/environments/local/config.json, src/components/TransactionFloater/index.js, src/components/TransactionFloater/transactionFloater.mod.scss, src/containers/TransactionFloaterContainer/index.js, src/routes/MarketList/components/NoMarkets/index.js
* `Transaction floater` component is using css modules now
* Added `react-immutable-proptypes` to babel plugin which deletes PropTypes in production
* Made local config use staging gnosisDB
* task/PM-586
* Styling bugs
- Compared TransactionFloater to previous version, everything looked OK
=> Task PM-586: Use CSS modules in components

src/routes/MarketList/store/actions/fetchMarkets.js
* Add filter to `processMarketResponse` if a collateral token specified in config
* Tested multiple collateral token in config and made sure everything is working
* I wasn't really sure if the right place to do it is selectors (previously filters were done there) or response processing, I chose response processing because I feel like we don't want to save unfiltered markets at all. Feel free to change if you disagree :)
=> Task PM-612: Filter markets by collateral token address from config

config/environments/staging/interface.config.json, src/components/Dashboard/Metrics/Layout.js, src/components/Dashboard/Metrics/index.js, src/components/Dashboard/index.js, src/containers/DashboardPage/index.js, src/containers/HeaderContainer/store/actions.js, src/selectors/blockchain.js
* Fix Profits
* Display WETH instead of ETH on Dashboard for Account Balance
* Fixes bug/PM-618
* /
* /
*Display WETH*
* Updated config, restarted webpack and it showed me my wrapped ether balance.
*Display Profits*
* Fixed a bug and it shows my profits now.
* WETH on the Dashboard might cause confusion
```
{
...
"collateralToken":  {
"address": "0xd19bce9f7693598a9fa1f94c548b20887a33f141",
"symbol": "WETH",
"icon": "/assets/img/icons/icon_etherTokens.svg"
},
...
}
```
=> bug/PM-618: Display WETH for Dashboard/Header and fix profits display

src/components/Header/index.js, src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/OutcomesSection/OutcomeSectionScalar/ScalarSlider/scalarSlider.mod.scss, src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/index.js, src/routes/MarketDetails/components/ExpandableViews/index.js
* Fix expandable not showing for tournaments without registration
* Backmerge return sign fix from master branch
* Fix scalar slider dot overlapping upper bound
* Fixes bug/PM-606
* https://github.com/gnosis/pm-trading-ui/pull/335
Tried to buy tokens on multiple scalar markets to check that overlapping doesn't happen again, tried different investment values to check return sign and visited market details page with locked/unlocked metamask to check expandable show condition
=> Bug PM-606: Fix overlap, fix expandable show condition, fix return sign

src/components/Header/index.js, src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/OutcomesSection/OutcomeSectionScalar/ScalarSlider/scalarSlider.mod.scss, src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/index.js, src/routes/MarketDetails/components/ExpandableViews/index.js
* Fix expandable not showing for tournaments without registration
* Backmerge return sign fix from master branch
* Fix scalar slider dot overlapping upper bound
* Fixes bug/PM-606
* https://github.com/gnosis/pm-trading-ui/pull/335
Tried to buy tokens on multiple scalar markets to check that overlapping doesn't happen again, tried different investment values to check return sign and visited market details page with locked/unlocked metamask to check expandable show condition
=> Bug PM-606: Fix overlap, fix expandable show condition, fix return sign PM-606 master

src/routes/MarketList/components/Filter/Form.js
* Set `destroyOnUnmount` to false for market list filter form
* Fixes BUG/PM-608
* https://github.com/gnosis/pm-trading-ui/pull/346
* None
I had chose different filters, then left the page and went back, the filters weren't reset
=> Bug PM-608: The filters doesn't remain through the navigation dev

config/config.json, config/environments/development/config.json, config/environments/local/config.json, config/environments/olympia/development/config.json, config/environments/staging/config.json, src/routes/MarketList/components/Filter/Form.js
* Set `destroyOnUnmount` to false for market list filter form
* Use new gnosisdb link: `tradingdb.staging.gnosisdev.com`
* Fixes BUG/PM-608
* https://github.com/gnosis/pm-trading-ui/pull/347
* None
I had chose different filters, then left the page and went back, the filters weren't reset
=> Bug PM-608: The filters doesn't remain through the navigation

src/containers/App/app.mod.scss, src/containers/InteractionButton/index.js
*  In some cases, `web3.eth.net.getId()` returns 0. So, targetNetworkId = 0, we don't have a network name for id 0 in `ETHEREUM_NETWORK_IDS`. This results to a reference to `undefined` and then we try to call `.toLowerCase()` and it throws an error
* Use an empty string in case `ETHEREUM_NETWORK_IDS[targetNetworkId]` is undefined
* Minor codestyle fixes
* Fix loader position
* Fixes bug/PM-625
* None
I tried to reproduce the bug from a ticket and I haven't succeeded.
=> Bug PM-625: Interface goes blank after selecting market and then logging in

src/containers/App/app.mod.scss, src/containers/InteractionButton/index.js
* In come cases, `web3.eth.net.getId()` returns 0. So, targetNetworkId = 0, we don't have a network name for id 0 in `ETHEREUM_NETWORK_IDS`. This results to a reference to `undefined` and then we try to call `.toLowerCase()` and it throws an error
* Use an empty string in case `ETHEREUM_NETWORK_IDS[targetNetworkId]` is undefined
* Minor codestyle fixes
* Fix loader position
* Fixes bug/PM-625
* None
I tried to reproduce the bug from a ticket and I haven't succeeded.
=> [BACKMERGE] Bug PM-625: Interface goes blank after selecting market and then logging in

src/store/utils/marketStatus.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
1.
=> [BACKMERGE] BUG: Fix marketStatus utils to use moment's utc correctly

src/store/utils/marketStatus.js
* Fixed usage of moment utc mode according to `moment.js` docs:
https://momentjs.com/docs/#/parsing/utc/
it should be `moment.utc()` instead of `moment().utc()`
* Use `isSameOrBefore` instead of `isBefore` for the case when resolution date is equal to `moment.utc().add('3 days')`
* Maybe a failing test 😄 
I ran the tests for 5 times and none failed
=> BUG: Fix marketStatus utils to use moment's utc correctly

src/routes/MarketDetails/store/actions/buyShares.js
* The error was  `TypeError: Converting circular structure to JSON` as a result of calling `JSON.stringify` on error object. I changed the action to pass only `.message` and not the whole object itself
* Fixes bug/PM-638
I tried to buy shares and rejected the buy tx. The interface didn't crash
=> BUG PM-638: Interface goes blank after rejecting buy tx

package.json, src/components/ModalContent/UnlockMetamask/UnlockMetamask.mod.scss, src/scss/vars.scss
* Update `redux-thunk`, `webpack`, `bootstrap-loader`
* Set outline to none when the button is focused
* Fix unlock metamask modal scss codestyle
* A focused button has the same effect as hovered one
* Fixes Bug/PM-614
* None
Checked styles of focused button in different modals
=> Bug PM-614: Modal close button has ugly outline effect

.bootstraprc, .travis.yml, config/environments/olympia/staging/config.json, env_build.sh, package.json, src/api/token.js, src/store/selectors/blockchain.js, webpack.prod.config.js
* When fetching balance, it returns a BigNumber and then after when you try to call Decimal() on this number, an error is raised. I added a `.toString()` call on balance inside api call.
* Fixes bug/PM-630
smoke test + checked if balances are shown right
=> Bug PM-630: Header/Dashboard shows 0 OLY balance

package.json, src/routes/MarketList/components/Filter/Form.js, src/routes/MarketList/store/selectors/filter.js
* Remove "show only my markets" filter
* Update dependencies
* None
Went to market list page and checked if the filter was removed
=> Task PM-668: Remove "Show Only My Markets" from Olympia and Mainnet

src/routes/Scoreboard/store/selectors/index.js
* The problem was in `meSelector` which was trying to do `.toLowerCase()` on an undefined account. I added a check for existence of the account
* Fixes bug/PM-681
* None
* browsed all the pages to check if there's an error
=> Bug PM-681: When the user goes to the Dashboard without being registered the interface goes blank

src/routes/Scoreboard/store/actions/fetchTournamentUserData.js, src/routes/Scoreboard/store/actions/fetchTournamentUsers.js, src/routes/Scoreboard/store/selectors/index.js
* Site crash fix when users who are not registered view the page.
* /
* /
* /
*Viewed Page as unregistered user*
* Worked, no more errors
* `normalizeHex` was introduced to deal with inconsistencies between trading-db, ethereum and other sources for addresses
/
=> Bug Hotfix: Error on unregistered accounts viewing the site

src/components/Outcome/OutcomeScalar/index.js, src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/OutcomesSection/OutcomeSectionScalar/ScalarSlider/index.js, src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/OutcomesSection/OutcomeSectionScalar/index.js
* The problem was because it was using divided bounds when it wasn't necessary. I fixed that and also made the calculations more intuitive in form's slider
* Fixes bug/PM-687
Made sure that the values in market list, details and form are consisten
=> Bug PM-687: Fix inconsistency between predicted scalar outcomes

src/components/Header/index.js
* Update token balance, tournament user data on account change
* Codestyle fixes according to new `eslint-config-airbnb` and `eslint-config-react` rules
* Fixes bug/PM-706
* None
Switched between accounts and the balance updated
=> Bug PM-706: OLYs are not refreshed

src/api/gnosis.js
The error was because it was trying to read `.contracts` of uninitialized gnosis.js read-only connection. I moved a promise from `getGnosisConnection` to a function where we can pass an instance and wait for it to load  
* Fixes bug/PM-710
* None
Refreshed the page like 15 times and it always logged me in
=> Bug PM-710: The interface sometimes forgets that the wallet is registered until you refresh the page

package-lock.json, package.json, src/components/ModalContent/RegisterWallet/index.js, src/containers/App/index.js, src/containers/BackdropProvider/index.js, src/containers/Modals/ModalRegisterWallet/index.js, src/store/actions/blockchain.js, src/store/reducers/blockchain.js, src/store/selectors/blockchain.js, src/store/selectors/blockchain.spec.js
* Remove `triedToConnect` because it's not reliable
* Add `isConnectedToBlockchain` to detect if both gnosis.js instances are initialized
* Close `registerWallet` modal if it turns out that user is already registered
* Codestyle fixes
* Update `css-loader`
* Change loader screen text to be more specific: from `Connecting` to `Connecting to the blockchain`
* Fixes bug/PM-712
* It's hard to say, maybe some problems with registration
*Open register mainnet address modal with unregistered account, then switch to a registered one*
Modal closes.
There were some problems with registration because gnosis.js read-only instance was initialized after we tried to get info from it. Now loader screen is shown until it is initialized. There are also one more bug with metamask integration that leaves the …
=> BUG PM-712: User is registered after rejecting Metamask pop up

src/containers/App/index.js
* Previously scoreboard's styles weren't imported and scoreboard looked weird
* Fixes bug/PM-738
* None
Checked that scoreboard shows fine
=> Bug PM-738: Scoreboard styles are not imported

config/mainnet/staging.json, package-lock.json, package.json, src/routes/Dashboard/components/Dashboard/UserSection/Holdings/Share.js, src/routes/Dashboard/containers/Dashboard/utils/calcShareWinnings.js, src/routes/MarketDetails/components/MarketDetail/Details/index.js, src/routes/MarketDetails/containers/MarketDetailPage/index.js, src/store/selectors/account/shares.js, src/store/selectors/market/shares.js
* Fix redeem winnings selectors, actions, etc 
* Fixes bug/PM-766
Redeemed winnings and the tx went through
=> BUG PM-766: Redeem winnings didn't work

package-lock.json, package.json, src/api/gnosis.js, src/components/DecimalValue/index.js, src/store/actions/blockchain.js, src/store/selectors/blockchain.js, src/store/selectors/blockchain.spec.js
* Pin pm-contracts version to 1.0.4 because newest versions have breaking changes
* Fixes #557 
I tried to reproduce the bug but I couldn't
=> #557 BUG: Pin pm-contracts version to 1.0.4, rename gnosis-js to pm-js and use pm-apollo-contracts

config/mainnet/staging.json, package-lock.json, package.json, src/assets/locales/en/translation.json, src/verification/onfido/components/Integration.js, src/verification/onfido/components/Welcome.js, src/verification/onfido/components/index.js, src/verification/onfido/containers/index.js
* Add verification translations
* Fix codestyle (I'm sorry, had to do this because some LOC didn't fit to my monitor)
* Fixes #554 
* https://github.com/gnosis/pm-trading-ui/pulls?utf8=%E2%9C%93&q=is%3Apr+translations
Gone through verification process, everything was translated
=> Feature: Verification translations

package.json, src/embedded/routes/EmbeddedView/api/index.js, src/embedded/routes/EmbeddedView/api/marketBuilders.js, src/embedded/routes/EmbeddedView/components/Market/Market.scss, src/embedded/routes/EmbeddedView/components/Market/MarketResolution.js, src/embedded/routes/EmbeddedView/components/Market/MarketStatus.js, src/embedded/routes/EmbeddedView/components/Market/MarketTrading.js, src/embedded/routes/EmbeddedView/components/Market/index.js, src/embedded/routes/EmbeddedView/components/Outcome/OutcomeCategorical/TrendingOutcomeCategorical/index.js, src/embedded/routes/EmbeddedView/components/Outcome/OutcomeCategorical/index.js, src/embedded/routes/EmbeddedView/components/Outcome/OutcomeCategorical/outcomeCategorical.scss, src/embedded/routes/EmbeddedView/components/Outcome/OutcomeColorBox/OutcomeColorBox.scss, src/embedded/routes/EmbeddedView/components/Outcome/OutcomeColorBox/index.js, src/embedded/routes/EmbeddedView/components/Outcome/OutcomeScalar/TrendingOutcomeScalar/index.js, src/embedded/routes/EmbeddedView/components/Outcome/OutcomeScalar/index.js, src/embedded/routes/EmbeddedView/components/Outcome/OutcomeScalar/outcomeScalar.scss, src/embedded/routes/EmbeddedView/components/Outcome/WinningOutcome/WinningOutcome.scss, src/embedded/routes/EmbeddedView/components/Outcome/WinningOutcome/index.js, src/embedded/routes/EmbeddedView/components/Outcome/index.js, src/embedded/routes/EmbeddedView/components/Outcome/utils/index.js, src/embedded/routes/EmbeddedView/components/index.js
The bundle size was big because it included pm.js and web3 stuff in it, even if it wasn't used, just imported in some component used. Maybe it could be done with some minifier/webpack settings, but I managed only to achieve it this way.
This PR reduces bundle size from 3.8mb to 673kb and build time from 24s to 8s
* Move Markets component to embedded route because we need to replace `calcLMSRMarginalPrice` from api there with our util function
* Move `marketBuilders` to the route
* Remove currencyName component in `MarketTrading component` because it imports api functions and thus pm.js and web3 stuff
* Maybe bugs :))
Compared this version on my local server with a deployed version, couldn't notice any difference
=> Isolate embedded components to reduce bundle size and decrease build time
