gnosis/pm-trading-ui

- src/actions/blockchain.js
- src/actions/market.js
- src/components/MarketBuySharesForm/index.js
- src/components/MarketDetail/index.js
https://github.com/facebook/react/issues/6895#issuecomment-281405036
> fix react swallowing errors (i hope)

- src/components/MarketMySharesForm/index.js
This PR sells ALL shares and not the rounded amount
> sell all shares fix

- src/api/rest.js
- src/components/FormBarChartRadioButton/formBarChartRadioButton.less
- src/components/FormBarChartRadioButton/index.js
- src/components/MarketBuySharesForm/index.js
https://gnosisltd.atlassian.net/browse/PM-13
> update outcome bars according to bet

- src/api/rest.js
- src/components/Dashboard/dashboard.less
- src/components/Dashboard/index.js
- src/utils/constants.js
Had to adjust CSS to fix linebreaks in Dashboard
> Bug PM-24: Date consistency in Dashboard/Details/Overview

- src/actions/market.js
- src/containers/App/index.js
> Feature PM-173 Automatically close modal

- src/actions/market.js
**Due Diligence**
**Description**
This PR checks if there is a higher difference between outcome prices when selling shares.
> PM-205 Check margin when selling shares

- src/components/MarketDetail/index.js
- src/components/ScalarSlider/index.js
- src/utils/shapes.js
This PR includes fix for showing closed/resolved message condition, eslint/codestyle fixes for ScalarSlider component, PropType fixes with change of type of Marginal Prices
> Bug PM-183 Fix closed/resolved message show conditions for markets

- src/components/Dashboard/index.js
This PR adds sorting to new markets widget and 5 market limit for the widgets. Also implements changes from this ticket: https://gnosisltd.atlassian.net/browse/PM-194
> Feature PM-14 PM-15 Fix dashboard market widgets

- src/components/OutcomeCategorical/index.js
- src/components/OutcomeCategorical/outcomeCategorical.less
> PM-185 Show only winning outcome for resolved markets

- src/components/MarketList/index.js
- src/components/ScalarSlider/index.js
This PR changes open/closed to open/ended, also adds calculations for markets overview
> Feature PM-53 Unity the terms open/ended

- src/components/Header/header.less
> BUG: Fix account alignment in Header

- src/components/MarketMySharesForm/index.js
- src/components/MarketMySharesForm/marketMySharesForm.less
- src/components/ScalarSlider/index.js
- src/components/layout/Hairline/index.js
**Due Diligence**
**Description**
I know this is a backmerge PR but I had to implement much more changes than I thought, due to the limit requirements.
The main problem that I had was the form autoupdate once the componentDidMount finished. I solved the problem introducing the default data on every form's init call.
AFTER:
> PM-330 [Backmerge] - Modify sell shares view

- src/actions/market.js
See https://github.com/gnosis/olympia-interface/pull/151
> Use Decimal.js to avoid sci notation string

- src/utils/helpers.js
See: https://github.com/gnosis/olympia-interface/pull/152
> [PM-376] Log hashes of transactions on start and sync in console

- src/components/Header/index.js
- src/containers/ModalNetworkCheck/index.js
- src/integrations/injectedWeb3.js
- src/integrations/metamask/index.js
- src/middlewares/Blockchain.js
- src/middlewares/Providers.js
**BEFORE:**
Changing account, balance, locking metamask is not recognized in the interface
**AFTER:**
Changing account, balance, locking metamask is recognized in the interface
Actual changes are in:
- `src/integrations/metamask/index.js`
- `src/integrations/injectedWeb3.js`
Other files are only eslint fixes
> Fix integrations watcher

- src/components/FormBarChartRadioButton/formBarChartRadioButton.less
- src/components/FormBarChartRadioButton/index.js
> PM-204: Fix percentage alignment 

- README.md
Default port has also been changed from 8000 to 5000
> Use Ganache-cli instead of TestRPC in README

- src/components/Dashboard/index.js
- src/components/layout/Block/index.css
- src/components/layout/Block/index.js
- src/components/layout/Bold/index.js
- src/components/layout/Hairline/index.js
- src/components/layout/Hairline/index.stories.js
- src/components/layout/Img/index.css
- src/components/layout/Img/index.js
- src/components/layout/PageFrame/index.css
- src/components/layout/PageFrame/index.js
- src/components/layout/Paragraph/index.css
- src/components/layout/Paragraph/index.js
- src/components/layout/Span/index.js
- src/components/layout/Subtitle/index.css
- src/components/layout/Subtitle/index.js
- src/components/layout/Title/index.css
- src/components/layout/Title/index.js
- src/config.json
- src/utils/analytics/ga.js
- src/utils/analytics/gaSend.js
- src/utils/analytics/init.js
This PR:
- Adds google analytics, layout components, missing function in Dashboard component
- Changes gnosisdb url
- Fixes app compilation 😆
> Backmerge: Change gnosisdb url, add layout components, GA, add missing function in Dashboard component

- package.json
- src/actions/notifications.js
- src/components/Spinner/Transaction.js
- src/components/TransactionFloater/index.js
* Use icon `cross` instead of inexistent icon `error`
* Update few packages
* bug/PM-595
- rejected buy, sell, redeem winnings TXs
> Bug PM-595: Fix crash when user rejects transaction

- src/routes/MarketList/components/Filter/Form.js
* Fix market status filter's name and sort labels
* Fixes bug/PM-611
* None
**BEFORE and AFTER:**
> BUG PM-611: Market status filters

- config/config.json
- src/api/gasPrice.js
- src/routes/MarketDetails/components/MarketDetail/index.js
- src/utils/features.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> [BACKMERGE] PM-445: implemented gas station for gasPrices (#333)

- config/environments/staging/interface.config.json
- src/components/Dashboard/Metrics/Layout.js
- src/components/Dashboard/Metrics/index.js
- src/components/Dashboard/index.js
- src/containers/DashboardPage/index.js
- src/containers/HeaderContainer/store/actions.js
- src/store/selectors/blockchain.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> [BACKMERGE] PM-618: Display WETH for Dashboard/Header (#334)

- src/components/Header/index.js
- src/components/ModalContent/AcceptTOS/index.js
- src/containers/HeaderContainer/store/selectors.js
- src/containers/InteractionButton/index.js
- src/containers/Modals/ModalAcceptTOS/index.js
- src/integrations/store/actions/index.js
- src/integrations/store/reducers/index.js
- src/integrations/store/selectors/index.js
- src/routes/MarketDetails/components/ExpandableViews/index.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> [BACKMERGE] BUG pm-620: interaction without accepting tos

- configuration.setup.js
- src/routes/MarketList/store/selectors/index.js
* PM-619: fix display of marketlist stats
* PM-619: fix another test
* PM-619: disable env logging for tests
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> [BACKMERGE] Bug/PM-619: Fix Marketlist Stats (#338)

- config/environments/mainnet/production/config.json
- config/environments/mainnet/staging/config.json
* Disable google analytics
* Fixes task/PM-642
* None
Google analytics library shouldn't be loaded, I checked and it wasn't
`/mainnet/production/config.js` and `/mainnet/staging/config.js`
```
"thirdparty": {
"googleAnalytics": {
"enabled": false
}
}
```
> Task PM-642: Disable Google Analytics

- config/interface.config.json
- src/actions/blockchain.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> BUG: Use abstraction from gnosis.js and not contract instance

- config/interface.config.json
- src/store/actions/blockchain.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> [BACKMERGE] BUG: Use abstraction from gnosis.js and not contract instance

- config/environments/olympia/production/interface.config.json
- config/environments/olympia/staging/interface.config.json
- src/components/Header/index.js
- src/components/ModalContent/RegisterWallet/index.js
- src/store/actions/account.js
- webpack.dev.config.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> Fix olympia configuration PM-627

- .bootstraprc
- .travis.yml
- config/environments/olympia/staging/config.json
- env_build.sh
- package.json
- src/api/token.js
- src/store/selectors/blockchain.js
- webpack.prod.config.js
* Configure olympia for testing PM-651
* Fix travis config PM-651
* Update build env script for olympia testing env PM-651
* Add missing bracket pm-651
* Add mini-css-extract-plugin PM-651
* Update bootstrap-loader settings PM-651
* Update webpack configuration PM-651
* Update whitelist PM-651
* Convert token balance to a string PM-630
* use tokenAmountString PM-630
* call .toString in api call PM-630
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> Bug PM-630: Header/Dashboard shows 0 OLY balance (#383)

- src/routes/Scoreboard/components/ClaimReward/index.js
- src/routes/Scoreboard/components/Layout.js
* Condition of showing "Reward Claim" box is now independent from claimStart and claimEnd config entries
* Fixes bug/PM-653
* May cause bugs with reward claiming 🤔 
Went to scoreboard page and checked if claim reward box is shown
> BUG PM-653: Fix the condition for showing reward claim box

- src/components/Header/index.js
* Remove transactions page link from header
* Fixes task/PM-657
* None
> Task PM-657: Remove TXs page link from header PM-657

- src/components/Header/Header.mod.scss
- src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/index.js
- src/routes/MarketDetails/containers/MarketDetailPage/index.js
* Fix "Connect a wallet" alignment
* Fix buy shares form validation: now it compares the amount you want to invest to your balance of market's collateral token
* Fixes bug/PM-655
* Cannot think of any.
* Checked the validation to be correct on trading/tournament interface
**BEFORE/AFTER:**
> Bug PM-655: Fix "Connect a wallet" alignment, fix buy shares validation

- src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/index.js
* Add WETH balance to ETH balance in case market's collateral token is ETH (WETH)
* Fixes bug/PM-666
Tried to invest ETH+WETH amount and it was successful
> Bug PM-666: User can not invest the WETH that he has + the ETH of his wallet

- src/routes/MarketDetails/components/MarketDetail/Details/Details.mod.scss
- src/routes/MarketDetails/components/MarketDetail/Details/index.js
* Add markdown viewer for market description
* Test market: 0x7f178553b13124efe19976126dab4002cc774433
* Probably some styling bugs, markdown allows to do a lot of stuff, and maybe some node can break styling
* Visited test market's details page, clicked the link in the description and it worked 😮
> Task PM-648: Add markdown viewer to market's description

- src/components/DecimalValue/index.js
- src/routes/Dashboard/components/Dashboard/Metrics/Metrics.mod.scss
- src/routes/Dashboard/components/Dashboard/Metrics/index.js
- src/routes/Dashboard/components/Dashboard/index.js
- src/routes/Dashboard/containers/Dashboard/actions.js
- src/routes/Dashboard/containers/Dashboard/selectors.js
- src/routes/Scoreboard/components/Layout.js
- src/routes/Scoreboard/components/Table/index.js
- src/routes/Scoreboard/store/selectors/index.js
* Add tournament-related data to metrics (Badge, rank)
* Fix users selector
* Few PropTypes fixes
* Maybe some bugs 😄 
* Compared the new dashboard to an old one
More things than need to be fixed:
- 
```
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
in withState(lifecycle(Dashboard)) (created by withState(withState(lifecycle(Dashboard))))
in withState(withState(lifecycle(Dashboard))) (created by Connect(withState(withState(lifecycle(Dashboard)))))
in Connect(withState(withState(lifecycle(Dashboard)))) (created by Route)
in Route (created by AppRouter)
in Switch (created by AppRouter)
in AppRouter …
```
> Bug fixes: Dashboard

- package.json
- src/routes/MarketDetails/components/ExpandableViews/MarketMySharesForm/SharesTable/ShareSellView/index.js
- src/routes/MarketDetails/components/ExpandableViews/MarketMySharesForm/SharesTable/ShareSellView/utils/index.js
- src/routes/MarketDetails/components/ExpandableViews/MarketMySharesForm/SharesTable/index.js
- src/routes/MarketDetails/components/ExpandableViews/MarketMySharesForm/index.js
- src/routes/MarketDetails/containers/MarketDetailPage/index.js
The bug was related to: https://github.com/erikras/redux-form/issues/2971
I took the solution from https://github.com/erikras/redux-form/issues/2971#issuecomment-389499758
* Add `sellFormHasErrors` prop
* Don't reset the form because it is reinitialized
* Move validate function to utils
* Fix default `selectedSellAmount` prop
* Fixes bug/PM-628
* Can't think of any. Maybe some bugs related with selling
I repeated all the steps from ticket description. Switched between shares and typed a different sell amounts, every time it correctly detected if there is an error or no
> Bug PM-628: Selling the min amount of tokens (0.000000000000000001) makes a transaction error in some markets

- config/environments/olympia/staging/interface.config.json
- src/components/ModalContent/ClaimReward/ClaimReward.mod.scss
- src/components/ModalContent/ClaimReward/index.js
- src/containers/Modals/ModalClaimReward/action.js
- src/containers/Modals/ModalClaimReward/api.js
- src/containers/Modals/ModalClaimReward/index.js
* Use `claimReward` contract address instead of `rewardToken`
* Fix modal styles
* Update rewardToken and claimReward contracts addresses
* Claimed rewards and the tx passed
> Bugfix: Reward claiming

- config/environments/olympia/development/interface.config.json
- config/environments/olympia/production/interface.config.json
- config/environments/olympia/staging/interface.config.json
* Update Icon for OLY-Tokens
* Update Configurations to work with reward claim contract on kovan for dev
* Fixes task/PM-673
* /
* /
> Task PM-673: Updated Icons and Configs

- .gitignore
- .travis.yml
- README.md
- package-lock.json
- package.json
- src/api/account.js
- src/api/gnosis.js
- src/api/market.js
* Use `npm ci` instead of `npm install` which should be faster: https://docs.npmjs.com/cli/ci
* Update dependencies (`gnosis-core-contracts` to `pm-contracts`, `gnosisjs` to `pm-js`)
* Failing builds 😆
> Task: Use npm ci in travis

- config/environments/olympia/staging/config.json
- package-lock.json
- package.json
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> Demo setup

- src/components/ModalContent/RegisterWallet/RegisterWallet.mod.scss
* Fix register mainnet address margins between legal checkboxes and eth annotation.
* Fixes bug/PM-691
* None
> Bug PM-691: Fix register mainnet address margins

- package-lock.json
- package.json
- src/integrations/store/selectors/index.js
- src/routes/MarketList/store/selectors/index.js
* In `hasAcceptedTermsAndConditions` add a condition for checking if interface is setup as a tournament with a registration, and then check if mainnet address is present
* Fixes bug/PM-702
Tried to buy shares and didn't see the message about TaC
> BUG PM-702: When the user hover over the buy/sell button a wrong message appears

- config/environments/olympia/development/interface.config.json
- config/environments/olympia/production/interface.config.json
- config/environments/olympia/staging/interface.config.json
- config/interface.config.json
- src/containers/Modals/ModalClaimReward/action.js
- src/containers/Modals/ModalClaimReward/index.js
- src/routes/Scoreboard/components/ClaimReward/index.js
- src/routes/Scoreboard/components/Layout.js
- src/routes/Scoreboard/components/Table/ScoreTable/table.js
* Separate `rewards` and `rewardClaiming` config entries
* Update configs in `olympia/`
* Fixes story/PM-699
* Fixes story/PM-700
* Cant think of any, maybe some bugs
* Checked the scoreboard to have updated values
* Checked general trading flow
> Task PM-699 & PM-700: Dappcon config preparations

- src/routes/MarketList/components/Filter/Form.js
- src/routes/MarketList/store/selectors/filter.js
* Remove my markets filter
* Fixes task/PM-695
Went to market list page and made sure that the filter was removed
> Task PM-695: Remove "My Markets" filter

- config/environments/olympia/staging/interface.config.json
- src/components/Header/index.js
* Change order of links in header, `Markets` before `Dashboard`
* Fixes task/PM-696
* None
* Checked order of links
> Task PM-696: Change order of links in header

- src/components/Form/OutcomeSelection/OutcomeBar.js
- src/components/Form/OutcomeSelection/index.js
- src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/OutcomesSection/OutcomeSectionScalar/index.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> Task PM-697: Remove percentage from scalar outcome selection

- .babelrc
- src/components/Countdown/index.js
* Fix countdown by passing `moment()`
* Add recompose to `babel-plugin-lodash` to decrease bundle size
* Fixes bug/PM-686
went to market details page and the countdown was updating every second
> Bug PM-686: Fix countdown

- src/api/gnosis.js
- src/components/ModalContent/RegisterWallet/index.js
- src/containers/InteractionButton/index.js
- src/containers/LegalCompliance/components/Form.js
* Fix order of setting `gnosis.js` instance to make sure it is set only after olympia contracts are imported
* Add `disableLegalCheck` and `disableWalletCheck` to `InteractionButton`
* Add `submitButtonOpts` to `LegalCompliance`
* Fixes bug/PM-705
Registered a new account and the loader was shown. Also made sure that balance checks are working
> Bug PM-705: Registration fixes

- package-lock.json
- src/routes/MarketDetails/components/MarketGraph/CategoricalGraph/index.js
- src/routes/MarketDetails/components/MarketGraph/ScalarGraph/index.js
* Limit YAxis ticks for categorical graph from 0 - 1
* Increase margins for scalar graph, so value + unit can fit
* Add custom formatter for scalar graph
* Fixes bug/PM-709
* None
Made sure that market graphs are displaying correctly for scalar and categorical markets
> Bug PM-709: MarketGraph fixes

- .eslintrc
- src/components/ModalContent/ClaimReward/index.js
- src/components/ModalContent/RegisterWallet/RegisterWallet.mod.scss
- src/components/ModalContent/RegisterWallet/index.js
- src/integrations/metamask/index.js
* Use `hasMetamask` util function to detect if user has metamask installed
* Show a note about insufficient balance in register wallet modal
* Turn off `"react/jsx-one-expression-per-line"` rule
* Fixes bug/PM-713
Created a new account and when I tried to register the annotation was shown.
> BUG PM-713: The interface does not notify the user that he has no ETH to register to the page

- src/containers/InteractionButton/index.js
- src/containers/InteractionButton/interactionButton.mod.scss
- src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/index.js
- src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/utils/index.js
* Fixed tooltip for disabled button, see: https://github.com/react-component/tooltip/issues/18 and https://github.com/ant-design/ant-design/commit/f5d697988a9e130379f7506eafee85acca3c030b#diff-186839a30bf8b9d67a4b10bf7c091d5fR88
* Change error message 'Your investment is invalid' to 'Please fill all mandatory fields'
* Eslint fixes
* Fixes task/PM-688
* https://github.com/gnosis/pm-trading-ui/pull/440
* None
*None of mandatory fields are filled*
* Tooltip 'Please fill all mandatory fields' is shown
*Investment value isn't filled*
* Tooltip 'Please enter an investment amount' is shown
*Outcome isn't selected*
* Tooltip 'Please select an outcome' is shown
> Task PM-688: Add a mandatory field mark for outcome and investment box choice

- config/environments/olympia/production/config.json
- config/environments/olympia/staging/config.json
- config/environments/olympia/staging/interface.config.json
- src/components/Outcome/OutcomeScalar/index.js
- src/components/Outcome/OutcomeScalar/outcomeScalar.mod.scss
- src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/OutcomesSection/OutcomeSectionScalar/ScalarSlider/index.js
- src/routes/MarketDetails/components/MarketDetail/Details/Details.mod.scss
- src/routes/MarketDetails/components/MarketDetail/Details/index.js
- src/utils/helpers.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> Merge hotfixes from dappcon olympia to qa branch

- src/store/selectors/blockchain.js
* This bug wouldn't allow you to buy shares and would show you insufficient balance error
* Fixes bug/PM-739
* None
Bough shares and the tx went through
> Bug PM-739: Fix token amount selector 

- src/components/Header/index.js
- src/components/ModalContent/OutcomePriceChanged.js
- src/components/ModalContent/TransactionsExplanation/TransactionExplanation.scss
- src/components/ModalContent/TransactionsExplanation/index.js
- src/containers/BackdropProvider/backdrop.scss
- src/containers/BackdropProvider/index.js
* Fix styling for tx explanation and outcomePriceChanged modals
* Add opacity transition for modals
* Fixes bug/PM-756
* None
> Bug PM-756: In some txns an error message appears when buying tokens

- config/olympia/production.json
- config/olympia/staging.json
* Update reward values
* Fixes story/PM-748
Made sure that the values are updated and correct.
`/olympia/staging.config`
`/olympia/production.config`
```
"levels": [
{ "value": 5, "minRank": 1, "maxRank": 1 },
{ "value": 4, "minRank": 2, "maxRank": 2 },
{ "value": 3, "minRank": 3, "maxRank": 3 },
{ "value": 2, "minRank": 4, "maxRank": 4 },
{ "value": 1, "minRank": 5, "maxRank": 5 },
{ "value": 0.2, "minRank": 6, "maxRank": 10 },
{ "value": 0.1, "minRank": 11, "maxRank": 50 }
]	  
```
> Story PM-748: Update reward values

- package-lock.json
- package.json
- src/routes/MarketDetails/components/ExpandableViews/MarketBuySharesForm/index.js
* Update `react-hot-loader`
* Check if investment value is greater or equal 1e-18
* Fixes bug/PM-759
* A little bit: https://github.com/gnosis/pm-trading-ui/pull/394
Tried to invest 1e-19 and it said that amount was invalid
> BUG PM-759: If user inputs an amount less than minimum amount in the BUY field, the BUY Tokens button is enabled

- package-lock.json
- src/components/DecimalValue/index.js
- src/components/Outcome/WinningOutcome/index.js
- src/components/Outcome/index.js
- src/containers/LegalCompliance/components/DocumentExplanation.js
- src/containers/LegalCompliance/components/DocumentField.js
- src/containers/LegalCompliance/components/Form.js
- src/integrations/store/selectors/index.js
- src/routes/MarketList/components/Markets/Market/index.js
* Fix `LegalCompliance` key warnings, also fix Text Explanation generation algorithm (previously " and " was prepended before the document list)
* Fix `Invalid Outcome` in `WinningOutcome` component
* Fix `DecimalValue` decimal.js proptype test
* Fix `CheckWalletConnection`, it would return true if tournament is not enabled but the user was registered previously (mainnetAddress stored in localStorage)
* Code style fixes 
* Fixes bug/PM-767
* Can't think of any, maybe some new interesting bugs
I made sure that:
* LegalCompliance doesn't show any warnings/errors
* Winning Outcome is shown correctly in scalar/categorical
* DecimalValue doesn't show PropType warnings anymore
* My tokens section is hidden if you're registered for tournament but not accepted legal documents
> BUG PM-767: DecimalValue proptype, LegalCompliance fixes, Invalid winning outcome fix 

- src/components/ModalContent/ClaimReward/index.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> Hotfix: Add missing space in Claim Reward modal

- config/olympia/production.json
- config/olympia/staging.json
- src/routes/Dashboard/components/Dashboard/Metrics/index.js
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> Task: Prepare olympia configuration

- src/routes/Scoreboard/components/ClaimReward/ClaimReward.scss
- src/routes/Scoreboard/components/Layout.js
- src/routes/Scoreboard/components/Layout.scss
- src/routes/Scoreboard/components/RewardClaimAddress/RewardClaim.scss
* Change flex-direction to column for RewardClaimInfo
* Fix code style of RewardClaimHandler's styles
* Change burger menu icon's position to absolute
* Fixes #519 
* #529 
Made sure that it looks good on mobile devices :)
> #519 Mobile scoreboard page

- src/components/Footer/Footer.scss
- src/containers/App/app.scss
* Add two media queries to change footer's position for mobile and tablets
* Fixes #518 
Resized my window and used chrome devtools to make sure it works
> Add media queries to change footer position

- src/assets/locales/de/translation.json
- src/assets/locales/en/translation.json
- src/components/Header/Balance/index.js
- src/components/Header/Layouts/DesktopHeader/index.js
- src/components/Header/Layouts/MobileHeader/index.js
- src/components/Header/ProviderIcon.js
- src/containers/App/index.js
- src/i18n.js
Reverts gnosis/pm-trading-ui#560 (🙈)
> Revert "Feature #546: Header Translations"

- src/assets/locales/en/translation.json
- src/components/ModalContent/ClaimReward/index.js
- src/components/ModalContent/InstallMetamask/index.js
- src/components/ModalContent/OutcomePriceChanged.js
- src/components/ModalContent/RegisterWallet/index.js
- src/components/ModalContent/RegisterWalletUport/index.js
- src/components/ModalContent/SwitchNetwork/index.js
- src/components/ModalContent/TransactionsExplanation/index.js
- src/components/ModalContent/UnlockMetamask/index.js
- src/components/ModalContent/Verification/index.js
- src/containers/LegalCompliance/components/DocumentExplanation.js
- src/containers/LegalCompliance/components/DocumentField.js
- src/containers/LegalCompliance/components/Form.js
* Implements Translations for all `ModalContent` components
* fixes #547
> Feature #547: Modal Translations

- .travis.yml
* task/PM-123
*Case 1*
*Case 2*
```
{
"feature": {
}
}
```
```
{
"feature": {
}
}
```
> Add assets deployment for management-staging and management-development
